// Engine barrel export — public API for CLI and MCP packages.
export { Indexer } from './indexer.js';
export type { Artifact, ArtifactInfo, IndexStats, RefreshResult, CallEdgeResult, ImpactResult, ImpactNode } from './indexer.js';
export { ArtifactResolver } from './artifact_resolver.js';
export type { ArtifactComparator } from './artifact_resolver.js';
export { resolve } from './smart_resolver.js';
export { SourceParser } from './source_parser.js';
export type { ClassDetail } from './source_parser.js';
export { Config } from './config.js';
export type { VersionStrategy } from './config.js';
export { DB } from './db/index.js';
export { PomParser } from './pom_parser.js';
export type { Dependency as PomDependency, PomInfo } from './pom_parser.js';
export { ProtoParser } from './proto_parser.js';
export type { ProtoInfo } from './proto_parser.js';
export { ClassParser } from './class_parser.js';
export { UnknownTagError } from './class_parser.js';
export type { ClassInfo } from './class_parser.js';
export * from './path_helpers.js';
export * from './constants.js';
export * from './sql_helpers.js';
export * from './bytecode_walker.js';
export * from './llm_format.js';
export * from './output.js';
export { explore } from './explore.js';
export type { ExploreInput, ExploreResult, ClassEntry, EdgeEntry, PathStep, ResourceEntry, DepEntry, IncludeSection } from './explore.js';
export { detectDependencies } from './project_detector.js';
export type { Dependency as ProjectDependency } from './project_detector.js';
export { getProjectContext } from './project_context.js';
export type { ProjectContext, ProjectCoordinate, ProjectDep, ResolvedTree } from './project_context.js';
